# NUMPY CHEATSHEET

## Importing numpy module using alias "np"

In [1]:
import numpy as np

## Create a numpy array using list

In [2]:
list1 = [1,2,3,4,5]
n1 = np.array(list1)
n1

array([1, 2, 3, 4, 5])

## Create a numpy array using 2-d list

In [3]:
list1 = [1,2,3,4,5]
list2 = [4,5,6,7,8]
n1 = np.array([list1,list2])
n1

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

## Attributes of nd array

In [4]:
print("Shape = ",n1.shape,"\nSize = ",n1.size,"\nDimension = ",n1.ndim,"\nDType",n1.dtype)

Shape =  (2, 5) 
Size =  10 
Dimension =  2 
DType int64


## Create 2 1-d arrays each of 5 elements and apply vector operations like addition or substraction

In [5]:
n1 = np.array([1,2,3,4,5,6,7,8,9,0])
n2 = np.array([1,0,2,9,3,8,4,7,5,6])

print("Addition",n1+n2)
print("Substraction",n1-n2)

Addition [ 2  2  5 13  8 14 11 15 14  6]
Substraction [ 0  2  1 -5  2 -2  3  1  4 -6]


## Create arrays of ones, zeros, identity matrix

In [6]:
c1 = np.zeros((2,3),dtype=int)
print(c1)
c1 = np.ones((2,3),dtype=int)
print(c1)
c1 = np.eye(3, dtype=int)
print(c1)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Create a matrix with all 1 values of shape (3,2)

In [7]:
c2 = np.ones((3,2),dtype=int)
print(c2)

[[1 1]
 [1 1]
 [1 1]]


### Create a 3d array of shape (4,3,2) with all 0 elements

In [8]:
c3 = np.zeros((4,3,2),dtype=int)
print(c3)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


### Create an identity matrix using eye method

In [9]:
c3 = np.eye(3,dtype=int)
print(c3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Comparison in numpy array

In [10]:
p1=np.array([10,20,30,40])
print(p1>15)

[False  True  True  True]


### Apply logical NOT Operation on an input array

In [11]:
c1 = np.eye(3, dtype=int)
c2 = np.logical_not(c1)
c3 = c2.astype(int)
print(c2,c3,)

[[False  True  True]
 [ True False  True]
 [ True  True False]] [[0 1 1]
 [1 0 1]
 [1 1 0]]


### Create an array of 3 elements 5, 7 and 9. Create deep and shallow copy pf this array.

In [12]:
x = np.array([5,7,9])
x1 = x.view()
x2 = x.copy()

print(x1,x2)

[5 7 9] [5 7 9]


### Broadcasting*

In [13]:
x3 = x+5
print(x3)

[10 12 14]


## Resizingof array

### Create a 2d array of shape 4x2 and reshape it into 2x4

In [14]:
list1 = [
    [1,2],
    [1,2],
    [1,2],
    [1,2],
]

y = np.array(list1)
z = y.reshape((2,4))
print(z)

[[1 2 1 2]
 [1 2 1 2]]


In [15]:
z1 = y.ravel()
print(z1)

[1 2 1 2 1 2 1 2]


## Indexing and slicing

### Consider a 2d array of shape 2x4 and apply indexing and slicing

In [16]:
print(z[:,0],z[1,:],z[:,1:3])

[1 1] [1 2 1 2] [[2 1]
 [2 1]]
